#!/bin/zsh
. ./shared.sh

# inspired from: https://github.com/holman/dotfiles/blob/master/bin/battery-status
status_emoji='❓'
time_til_discharge="∞"
using_ac=0
if [ "$(pmset -g ac)" = "No adapter attached." ]; then
  status_emoji='🔋'
  using_ac=1
else
  status_emoji='🔌'
fi

if [ $using_ac -eq 1 ]; then
  time_til_discharge=$(
    pmset -g batt | \
    tail -1 | cut -f2 | awk -F"; " '{print $3}' | cut -d' ' -f1
  )
fi

cprint "system using $status_emoji, time remaning: $ct_yellow$time_til_discharge"
